# Generated by Django 5.0.6 on 2024-07-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedlink',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
