# Generated by Django 5.0.6 on 2024-07-22 23:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapedlink_url_alter_scrapedpage_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedpage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='scrapedpage',
            unique_together={('user', 'url')},
        ),
    ]
